export const tags = {
   astro: { name: 'Astro', icon: '/assets/logos/astro.svg', color: '#FF5D00' },
   javascript: { name: 'JavaScript', icon: '/assets/logos/javascript.svg', color: '#F7DF1E' },
   typescript: { name: 'TypeScript', icon: '/assets/logos/typescript.svg', color: '#3178C6' },
   react: { name: 'React', icon: '/assets/logos/react.svg', color: '#61DAFB' },
   nodejs: { name: 'Node.js', icon: '/assets/logos/nodejs.svg', color: '#339933' },
   mongodb: { name: 'MongoDB', icon: '/assets/logos/mongodb.svg', color: '#47A248' },
   postgresql: { name: 'PostgreSQL', icon: '/assets/logos/postgresql.svg', color: '#336791' },
   mysql: { name: 'MySQL', icon: '/assets/logos/mysql.svg', color: '#4479A1' },
   restapi: { name: 'REST API', icon: '/assets/logos/rest-api.svg', color: '#6E6E6E' },
   html5: { name: 'HTML5', icon: '/assets/logos/html5.svg', color: '#E34F26' },
   css3: { name: 'CSS3', icon: '/assets/logos/css3.svg', color: '#1572B6' },
   tailwindcss: { name: 'Tailwind CSS', icon: '/assets/logos/tailwindcss.svg', color: '#06B6D4' },
   materialui: { name: 'Material UI', icon: '/assets/logos/material-ui.svg', color: '#0081CB' },
   bootstrap: { name: 'Bootstrap', icon: '/assets/logos/bootstrap.svg', color: '#7952B3' },
   git: { name: 'Git', icon: '/assets/logos/git.svg', color: '#F05032' },
   github: { name: 'GitHub', icon: '/assets/logos/github.svg', color: '#181717' },
   docker: { name: 'Docker', icon: '/assets/logos/docker.svg', color: '#2496ED' },
   aws: { name: 'AWS', icon: '/assets/logos/aws.svg', color: '#FF9900' },
   java: { name: 'Java', icon: '/assets/logos/java.svg', color: '#007396' },
   springboot: { name: 'Spring Boot', icon: '/assets/logos/spring-boot.svg', color: '#6DB33F' },
   python: { name: 'Python', icon: '/assets/logos/python.svg', color: '#3776AB' },
   vuejs: { name: 'Vue.js', icon: '/assets/logos/vuejs.svg', color: '#4FC08D' },
   angular: { name: 'Angular', icon: '/assets/logos/angular.svg', color: '#DD0031' },
   sass: { name: 'Sass', icon: '/assets/logos/sass.svg', color: '#CC6699' },
   figma: { name: 'Figma', icon: '/assets/logos/figma.svg', color: '#F24E1E' },
   photoshop: { name: 'Photoshop', icon: '/assets/logos/photoshop.svg', color: '#31A8FF' },
   illustrator: { name: 'Illustrator', icon: '/assets/logos/illustrator.svg', color: '#FF9A00' },
   vue: { name: 'Vue', icon: '/assets/logos/vue.svg', color: '#4FC08D' },
   graphql: { name: 'GraphQL', icon: '/assets/logos/graphql.svg', color: '#E10098' },
 };