export const tags = {
   javascript: { name: 'JavaScript', icon: 'javascript.svg' },
   typescript: { name: 'TypeScript', icon: 'typescript.svg' },
   react: { name: 'React', icon: 'react.svg' },
   nodejs: { name: 'Node.js', icon: 'nodejs.svg' },
   mongodb: { name: 'MongoDB', icon: 'mongodb.svg' },
   postgresql: { name: 'PostgreSQL', icon: 'postgresql.svg' },
   mysql: { name: 'MySQL', icon: 'mysql.svg' },
   restapi: { name: 'REST API', icon: 'rest-api.svg' },
   html5: { name: 'HTML5', icon: 'html5.svg' },
   css3: { name: 'CSS3', icon: 'css3.svg' },
   tailwindcss: { name: 'Tailwind CSS', icon: 'tailwindcss.svg' },
   materialui: { name: 'Material UI', icon: 'material-ui.svg' },
   bootstrap: { name: 'Bootstrap', icon: 'bootstrap.svg' },
   git: { name: 'Git', icon: 'git.svg' },
   github: { name: 'GitHub', icon: 'github.svg' },
   docker: { name: 'Docker', icon: 'docker.svg' },
   aws: { name: 'AWS', icon: 'aws.svg' },
   java: { name: 'Java', icon: 'java.svg' },
   springboot: { name: 'Spring Boot', icon: 'spring-boot.svg' },
   python: { name: 'Python', icon: 'python.svg' },
   vuejs: { name: 'Vue.js', icon: 'vuejs.svg' },
   angular: { name: 'Angular', icon: 'angular.svg' },
   sass: { name: 'Sass', icon: 'sass.svg' },
   figma: { name: 'Figma', icon: 'figma.svg' },
   photoshop: { name: 'Photoshop', icon: 'photoshop.svg' },
   illustrator: { name: 'Illustrator', icon: 'illustrator.svg' },
 };